// Auto-generated from the official ATS MDCAT question bank (Mock Test 1).
import { Question } from "./types";

export const TEST_1_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "biology",
    text: "Which of the following is a monosaccharide with ketone group?",
    options: ["Glucose", "Fructose", "Galactose", "Ribose"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 2,
    subject: "biology",
    text: "Peptide bond is formed between:",
    options: ["Two amino groups", "Two carboxyl groups", "Amino group and carboxyl group", "R-group and amino group"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 3,
    subject: "biology",
    text: "Which bond maintains secondary structure of protein?",
    options: ["Peptide bond", "Hydrogen bond", "Disulfide bond", "Ionic bond"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 4,
    subject: "biology",
    text: "Saturated fatty acids have:",
    options: ["One double bond", "Multiple double bonds", "No double bond", "Triple bond"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 5,
    subject: "biology",
    text: "DNA differs from RNA in having:",
    options: ["Ribose sugar", "Uracil", "Deoxyribose sugar", "Single strand"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 6,
    subject: "biology",
    text: "The ratio of hydrogen to oxygen in carbohydrates is:",
    options: ["1:2", "2:1", "1:1", "3:1"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 7,
    subject: "biology",
    text: "Which is NOT a polysaccharide?",
    options: ["Starch", "Glygogen", "Cellulose", "Sucrose"],
    correctIndex: 3,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 8,
    subject: "biology",
    text: "Tertiary structure of protein is stabilized by:",
    options: ["Only hydrogen bonds", "Only disulfide bonds", "Hydrophobic interactions, H-bonds, ionic bonds, disulfide bonds", "Peptide bonds only"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 9,
    subject: "biology",
    text: "Cholesterol is a:",
    options: ["Phospholipid", "Steroid", "Triglyceride", "Wax"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 10,
    subject: "biology",
    text: "Nucleotides are linked by:",
    options: ["Glycosidic bond", "Peptide bond", "Phosphodiester bond", "Ester bond"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 11,
    subject: "biology",
    text: "Which amino acid is non-polar?",
    options: ["Lysine", "Aspartic acid", "Leucine", "Serine"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 12,
    subject: "biology",
    text: "Lactose is made of:",
    options: ["Glucose + Glucose", "Glucose + Fructose", "Glucose + Galactose", "Fructose + Galactose"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 13,
    subject: "biology",
    text: "The storage form of glucose in animals is:",
    options: ["Starch", "Cellulose", "Glycogen", "Chitin"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 14,
    subject: "biology",
    text: "Which level of protein structure gives functional protein?",
    options: ["Primary", "Secondary", "Tertiary", "Quaternary"],
    correctIndex: 3,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 15,
    subject: "biology",
    text: "Purines include:",
    options: ["Cytosine, Thymine", "Adenine, Guanine", "Uracil, Thymine", "Adenine, Cytosine"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 16,
    subject: "biology",
    text: "In DNA, Adenine pairs with Thymine by:",
    options: ["3 H-bonds", "2 H-bonds", "1 H-bond", "Covalent bond"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 17,
    subject: "biology",
    text: "Which is a reducing sugar?",
    options: ["Sucrose", "Maltose", "Starch", "Glycogen"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 18,
    subject: "biology",
    text: "Sickle cell anemia is due to change in:",
    options: ["Primary structure of hemoglobin", "Secondary structure", "DNA structure", "RNA structure"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 19,
    subject: "biology",
    text: "Waxes are esters of:",
    options: ["Fatty acid + glycerol", "Fatty acid + long chain alcohol", "Glycerol + phosphate", "Fatty acid + sphingosine"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 20,
    subject: "biology",
    text: "The building block of nucleic acid is:",
    options: ["Nucleoside", "Nucleotide", "Nitrogen base", "Pentose sugar"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 21,
    subject: "biology",
    text: "α-Helix and β-pleated sheet are examples of:",
    options: ["Primary structure", "Secondary structure", "Tertiary structure", "Quaternary structure"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 22,
    subject: "biology",
    text: "Which vitamin is water soluble?",
    options: ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin K"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 23,
    subject: "biology",
    text: "Chitin is a polymer of:",
    options: ["Glucose", "N-acetyl glucosamine", "Galactose", "Fructose"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 24,
    subject: "biology",
    text: "Unsaturated fats are liquid at room temp due to:",
    options: ["Single bonds", "Double bonds causing kinks", "Short chains", "High melting point"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 25,
    subject: "biology",
    text: "DNA is negatively charged due to:",
    options: ["Sugar", "Nitrogen base", "Phosphate group", "Hydrogen bond"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 26,
    subject: "biology",
    text: "Which test is used for reducing sugars?",
    options: ["Iodine test", "Biuret test", "Benedict’s test", "Sudan III test"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 27,
    subject: "biology",
    text: "Phospholipids have:",
    options: ["3 fatty acids", "2 fatty acids + phosphate", "1 fatty acid + glycerol", "No fatty acid"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 28,
    subject: "biology",
    text: "Denaturation of protein affects:",
    options: ["Primary structure", "Peptide bonds", "2°, 3°, 4° structure", "Amino acid sequence"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 29,
    subject: "biology",
    text: "Net ATP gain from one glucose in aerobic respiration:",
    options: ["2", "32", "36-38", "40"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 30,
    subject: "biology",
    text: "Site of Krebs cycle is:",
    options: ["Cytoplasm", "Mitochondrial matrix", "Inner mitochondrial membrane", "Chloroplast stroma"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 31,
    subject: "biology",
    text: "Oxygen in photosynthesis comes from:",
    options: ["CO2", "H2O", "Glucose", "Chlorophyll"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 32,
    subject: "biology",
    text: "Non-cyclic photophosphorylation produces:",
    options: ["ATP only", "NADPH only", "ATP + NADPH + O2", "Glucose"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 33,
    subject: "biology",
    text: "Final electron acceptor in ETC of mitochondria:",
    options: ["NAD+", "FAD", "O2", "Cytochrome c"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 34,
    subject: "biology",
    text: "Glycolysis occurs in:",
    options: ["Mitochondria", "Cytoplasm", "Chloroplast", "Nucleus"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 35,
    subject: "biology",
    text: "Calvin cycle occurs in:",
    options: ["Grana", "Thylakoid lumen", "Stroma", "Cytoplasm"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 36,
    subject: "biology",
    text: "Which is NOT part of light dependent reaction?",
    options: ["Photolysis of water", "ATP synthesis", "CO2 fixation", "NADPH formation"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 37,
    subject: "biology",
    text: "Chemiosmosis in mitochondria generates ATP due to:",
    options: ["Substrate level phosphorylation", "Proton gradient", "Electron transfer", "Oxygen consumption"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 38,
    subject: "biology",
    text: "How many CO2 molecules released in Krebs cycle per glucose?",
    options: ["2", "4", "6", "1"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 39,
    subject: "biology",
    text: "C4 plants show Kranz anatomy in:",
    options: ["Root", "Stem", "Leaf", "Flower"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 40,
    subject: "biology",
    text: "Alcoholic fermentation end products:",
    options: ["Lactic acid + CO2", "Ethanol + CO2", "Pyruvate + ATP", "Acetyl CoA + H2O"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 41,
    subject: "biology",
    text: "Z-scheme is related to:",
    options: ["Dark reaction", "Light reaction", "Glycolysis", "Krebs cycle"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 42,
    subject: "biology",
    text: "Link reaction converts:",
    options: ["Glucose to pyruvate", "Pyruvate to Acetyl CoA", "Acetyl CoA to citrate", "Citrate to oxaloacetate"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 43,
    subject: "biology",
    text: "RUBISCO has affinity for:",
    options: ["CO2 only", "O2 only", "Both CO2 and O2", "H2O"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 44,
    subject: "biology",
    text: "First stable product of C3 cycle:",
    options: ["RuBP", "PGA", "PGAL", "Glucose"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 45,
    subject: "biology",
    text: "How many ATP used in glycolysis?",
    options: ["1", "2", "4", "6"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 46,
    subject: "biology",
    text: "NADH from glycolysis yields how many ATP in ETC?",
    options: ["2", "3", "4", "6"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 47,
    subject: "biology",
    text: "Photorespiration occurs in:",
    options: ["C3 plants", "C4 plants", "CAM plants", "All plants"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 48,
    subject: "biology",
    text: "Cytochrome complex in photosynthesis is:",
    options: ["PSI", "PSII", "Cyt b6f", "ATP synthase"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 49,
    subject: "biology",
    text: "Which pigment absorbs blue-red light best?",
    options: ["Chlorophyll a", "Chlorophyll b", "Carotenoids", "Xanthophyll"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 50,
    subject: "biology",
    text: "Substrate level phosphorylation occurs in:",
    options: ["Glycolysis + Krebs", "ETC only", "Calvin cycle", "Light reaction"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 51,
    subject: "biology",
    text: "Capsid of virus is made of:",
    options: ["Lipid", "Protein", "Carbohydrate", "DNA"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 52,
    subject: "biology",
    text: "Bacteriophage infects:",
    options: ["Plants", "Animals", "Bacteria", "Fungi"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 53,
    subject: "biology",
    text: "Retroviruses contain:",
    options: ["DNA", "RNA + Reverse transcriptase", "Both DNA & RNA", "No nucleic acid"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 54,
    subject: "biology",
    text: "Lytic cycle results in:",
    options: ["Host survival", "Host cell lysis", "Prophage formation", "Lysogeny"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 55,
    subject: "biology",
    text: "Tobacco Mosaic Virus has:",
    options: ["DNA", "ssRNA", "dsRNA", "Protein only"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 56,
    subject: "biology",
    text: "Prions are:",
    options: ["Viruses", "Infectious proteins", "Bacteria", "Fungi"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 57,
    subject: "biology",
    text: "HIV attacks:",
    options: ["RBCs", "T-helper cells", "B-cells", "Platelets"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 58,
    subject: "biology",
    text: "Viroids consist of:",
    options: ["DNA + Protein", "RNA only", "Protein only", "Lipid + RNA"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 59,
    subject: "biology",
    text: "Temperate phage causes:",
    options: ["Lytic cycle", "Lysogenic cycle", "Both lytic & lysogenic", "No infection"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 60,
    subject: "biology",
    text: "Envelope of virus is derived from:",
    options: ["Viral DNA", "Host cell membrane", "Capsid", "Ribosome"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 61,
    subject: "biology",
    text: "Vaccine for Hepatitis B is made from:",
    options: ["Live virus", "Killed virus", "Viral protein antigen", "Viral RNA"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 62,
    subject: "biology",
    text: "Smallest virus is:",
    options: ["Pox virus", "Polio virus", "TMV", "HIV"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 63,
    subject: "biology",
    text: "Coronavirus genome is:",
    options: ["dsDNA", "ssDNA", "+ssRNA", "-ssRNA"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 64,
    subject: "biology",
    text: "Mad cow disease is caused by:",
    options: ["Virus", "Bacteria", "Prion", "Viroid"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 65,
    subject: "biology",
    text: "Viral replication occurs inside host because viruses lack:",
    options: ["DNA", "RNA", "Ribosomes", "Capsid"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 66,
    subject: "biology",
    text: "Oncogenic viruses cause:",
    options: ["AIDS", "Cancer", "Hepatitis", "Influenza"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 67,
    subject: "biology",
    text: "Cell theory does NOT state:",
    options: ["All organisms made of cells", "Cell is basic unit of life", "All cells arise from pre-existing cells", "All cells have nucleus"],
    correctIndex: 3,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 68,
    subject: "biology",
    text: "Fluid mosaic model was given by:",
    options: ["Robert Hooke", "Singer & Nicolson", "Schleiden & Schwann", "Virchow"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 69,
    subject: "biology",
    text: "Powerhouse of cell:",
    options: ["Chloroplast", "Mitochondria", "Ribosome", "Golgi"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 70,
    subject: "biology",
    text: "Ribosomes are made of:",
    options: ["DNA + Protein", "rRNA + Protein", "mRNA + Protein", "tRNA + Protein"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 71,
    subject: "biology",
    text: "Function of lysosome:",
    options: ["Protein synthesis", "Intracellular digestion", "Lipid synthesis", "Photosynthesis"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 72,
    subject: "biology",
    text: "Cell wall of plants is made of:",
    options: ["Chitin", "Cellulose", "Peptidoglycan", "Glycogen"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 73,
    subject: "biology",
    text: "80S ribosomes are found in:",
    options: ["Prokaryotes", "Mitochondria", "Eukaryotic cytoplasm", "Chloroplast"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 74,
    subject: "biology",
    text: "Which organelle has its own DNA?",
    options: ["Ribosome", "Lysosome", "Mitochondria", "Golgi"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 75,
    subject: "biology",
    text: "Cytoskeleton component for cell movement:",
    options: ["Microfilaments", "Intermediate filaments", "Microtubules", "Both A & C"],
    correctIndex: 3,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 76,
    subject: "biology",
    text: "Plasma membrane is:",
    options: ["Permeable", "Impermeable", "Selectively permeable", "Semipermeable only to water"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 77,
    subject: "biology",
    text: "Function of SER:",
    options: ["Protein synthesis", "Lipid synthesis & detoxification", "ATP synthesis", "DNA replication"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 78,
    subject: "biology",
    text: "Nucleolus is site of:",
    options: ["DNA synthesis", "rRNA synthesis", "mRNA synthesis", "tRNA synthesis"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 79,
    subject: "biology",
    text: "Gap junctions are found in:",
    options: ["Plant cells", "Animal cells", "Bacterial cells", "Fungal cells"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 80,
    subject: "biology",
    text: "Plasmodesmata connect:",
    options: ["Animal cells", "Plant cells", "Bacterial cells", "Virus to host"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 81,
    subject: "biology",
    text: "G1, S, G2 phases are part of:",
    options: ["Mitosis", "Meiosis", "Interphase", "Cytokinesis"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 82,
    subject: "chemistry",
    text: "1 mole of H₂SO₄ contains how many oxygen atoms?",
    options: ["6.02 × 10²³", "2 × 6.02 × 10²³", "4 × 6.02 × 10²³", "7 × 6.02 × 10²³"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 83,
    subject: "chemistry",
    text: "Empirical formula of benzene is:",
    options: ["C₆H₆", "CH", "C₂H₂", "C₃H₃"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 84,
    subject: "chemistry",
    text: "Limiting reactant is the one which:",
    options: ["Is in excess", "Is consumed first", "Has highest mass", "Gives maximum product"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 85,
    subject: "chemistry",
    text: "Moles in 22 g CO₂ are:",
    options: ["0.5", "1", "2", "4"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 86,
    subject: "chemistry",
    text: "Avogadro’s number represents:",
    options: ["Atoms in 1 g", "Molecules in 1 mole", "Electrons in 1 atom", "Protons in 1 mole"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 87,
    subject: "chemistry",
    text: "Molar volume at STP is:",
    options: ["24.0 L", "22.4 L", "20.0 L", "18.0 L"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 88,
    subject: "chemistry",
    text: "Stoichiometry is based on:",
    options: ["Law of conservation of mass", "Periodic law", "Boyle’s law", "Avogadro’s hypothesis"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 89,
    subject: "chemistry",
    text: "Molecular mass is sum of:",
    options: ["Atomic numbers", "Neutrons only", "Atomic masses of atoms", "Protons only"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 90,
    subject: "chemistry",
    text: "SI unit of amount of substance is:",
    options: ["Gram", "Mole", "Liter", "Atom"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 91,
    subject: "chemistry",
    text: "Percentage of oxygen in water is:",
    options: ["11.2%", "33.3%", "88.8%", "50%"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 92,
    subject: "chemistry",
    text: "Empirical formula from 40% C, 6.7% H, 53.3% O is:",
    options: ["CHO", "CH₂O", "C₂H₄O₂", "CH₃O"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 93,
    subject: "chemistry",
    text: "2H₂ + O₂ → 2H₂O: 4 moles H₂ produce:",
    options: ["2", "4", "6", "8"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 94,
    subject: "chemistry",
    text: "Significant figures in 0.00580:",
    options: ["2", "3", "4", "5"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 95,
    subject: "chemistry",
    text: "Isotopes have same:",
    options: ["Mass number", "Neutrons", "Atomic number", "Nucleons"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 96,
    subject: "chemistry",
    text: "1 mole of any substance contains:",
    options: ["6.02 × 10²² particles", "6.02 × 10²³ particles", "3.01 × 10²³ particles", "1.66 × 10⁻²⁴ particles"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 97,
    subject: "chemistry",
    text: "Cathode rays are:",
    options: ["Protons", "Electrons", "Neutrons", "Alpha particles"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 98,
    subject: "chemistry",
    text: "Rutherford discovered:",
    options: ["Electron", "Nucleus", "Neutron", "Proton"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 99,
    subject: "chemistry",
    text: "Dual nature of electron proposed by:",
    options: ["Bohr", "de Broglie", "Planck", "Dalton"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 100,
    subject: "chemistry",
    text: "Heisenberg uncertainty principle involves:",
    options: ["Energy & time", "Position & momentum", "Mass & velocity", "Charge & mass"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 101,
    subject: "chemistry",
    text: "Shape of orbital is determined by:",
    options: ["n", "l", "m", "s"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 102,
    subject: "chemistry",
    text: "Max electrons in n = 3 shell:",
    options: ["8", "18", "32", "2"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 103,
    subject: "chemistry",
    text: "Cr (Z = 24) configuration is:",
    options: ["4s² 3d⁴", "4s¹ 3d⁵", "4s² 3d⁶", "4s⁰ 3d⁶"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 104,
    subject: "chemistry",
    text: "Invalid quantum set:",
    options: ["n = 2, l = 1", "n = 3, l = 3", "n = 4, l = 2", "n = 1, l = 0"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 105,
    subject: "chemistry",
    text: "Electron energy in H atom is:",
    options: ["Zero", "Positive", "Negative", "Infinite"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 106,
    subject: "chemistry",
    text: "Visible hydrogen spectrum is:",
    options: ["Lyman", "Balmer", "Paschen", "Brackett"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 107,
    subject: "chemistry",
    text: "Pauli principle states:",
    options: ["Same energy levels", "No two electrons have same 4 quantum numbers", "Same orbitals always", "Electrons repel"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 108,
    subject: "chemistry",
    text: "d-subshell has:",
    options: ["5 orbitals", "3 orbitals", "7 orbitals", "1 orbital"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 109,
    subject: "chemistry",
    text: "X-rays are produced when:",
    options: ["Electrons hit metal", "Protons move", "Neutrons decay", "Alpha particles stop"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 110,
    subject: "chemistry",
    text: "Tritium is hydrogen with mass number:",
    options: ["1", "2", "3", "4"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 111,
    subject: "chemistry",
    text: "e/m ratio discovered by:",
    options: ["Thomson", "Rutherford", "Bohr", "Millikan"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 112,
    subject: "chemistry",
    text: "Boyle’s law is:",
    options: ["V ∝ T", "P ∝ V", "PV = constant", "P ∝ T"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 113,
    subject: "chemistry",
    text: "Ideal gas equation:",
    options: ["PV = nRT", "P₁V₁ = P₂V₂", "V/T = constant", "P/T = constant"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 114,
    subject: "chemistry",
    text: "Gas molecules have:",
    options: ["Large volume", "No motion", "Negligible volume", "Strong forces"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 115,
    subject: "chemistry",
    text: "Partial pressure law:",
    options: ["Charles law", "Dalton’s law", "Boyle’s law", "Graham’s law"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 116,
    subject: "chemistry",
    text: "1 atm equals:",
    options: ["750 mmHg", "760 mmHg", "700 mmHg", "800 mmHg"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 117,
    subject: "chemistry",
    text: "Vapor pressure depends on:",
    options: ["Surface area", "Temperature", "Volume", "Mass"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 118,
    subject: "chemistry",
    text: "Boiling point decreases when:",
    options: ["Pressure increases", "Pressure decreases", "Volume increases", "Mass increases"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 119,
    subject: "chemistry",
    text: "Surface tension is due to:",
    options: ["Adhesion", "Cohesion", "Gravity", "Pressure"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 120,
    subject: "chemistry",
    text: "Viscosity decreases with:",
    options: ["Temperature increase", "Pressure increase", "Volume increase", "Density increase"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 121,
    subject: "chemistry",
    text: "Highest boiling point:",
    options: ["H₂O", "H₂S", "H₂Se", "H₂Te"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 122,
    subject: "chemistry",
    text: "Atoms in simple cubic unit cell:",
    options: ["1", "2", "4", "6"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 123,
    subject: "chemistry",
    text: "Diamond is:",
    options: ["Ionic solid", "Molecular solid", "Covalent network solid", "Metallic solid"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 124,
    subject: "chemistry",
    text: "Coordination number of FCC:",
    options: ["6", "8", "12", "4"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 125,
    subject: "chemistry",
    text: "Graphite conducts due to:",
    options: ["Ions", "Free electrons", "Protons", "Neutrons"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 126,
    subject: "chemistry",
    text: "Packing efficiency of BCC:",
    options: ["52%", "68%", "74%", "90%"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 127,
    subject: "physics",
    text: "A body can have zero velocity but non-zero acceleration when:",
    options: ["moving in straight line", "at highest point in projectile", "uniform motion", "rest in equilibrium"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 128,
    subject: "physics",
    text: "Two forces 10N and 10N can produce resultant:",
    options: ["only 0N", "only 20N", "any value between 0N and 20N", "only 10N"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 129,
    subject: "physics",
    text: "If net force on a body is zero, it means:",
    options: ["body must stop", "body cannot move", "velocity remains constant", "acceleration increases"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 130,
    subject: "physics",
    text: "Work done by centripetal force is zero because:",
    options: ["force is zero", "displacement is zero", "force is perpendicular to velocity", "mass is zero"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 131,
    subject: "physics",
    text: "Inertia of a body increases if:",
    options: ["velocity increases", "mass increases", "force increases", "acceleration increases"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 132,
    subject: "physics",
    text: "A passenger leans forward when bus stops suddenly due to:",
    options: ["force", "inertia", "gravity", "friction"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 133,
    subject: "physics",
    text: "Cross product becomes maximum when vectors are:",
    options: ["parallel", "45°", "perpendicular", "opposite"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 134,
    subject: "physics",
    text: "Scalar quantity among:",
    options: ["displacement", "force", "work", "velocity"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 135,
    subject: "physics",
    text: "If A = -B, then angle between them is:",
    options: ["0°", "45°", "90°", "180°"],
    correctIndex: 3,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 136,
    subject: "physics",
    text: "A body in uniform circular motion has:",
    options: ["constant velocity", "constant speed", "zero acceleration", "zero force"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 137,
    subject: "physics",
    text: "Torque depends on:",
    options: ["only force", "only distance", "force and perpendicular distance", "mass only"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 138,
    subject: "physics",
    text: "If radius doubles and speed remains constant, centripetal force becomes:",
    options: ["double", "half", "four times", "unchanged"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 139,
    subject: "physics",
    text: "Momentum is conserved when:",
    options: ["velocity constant", "no external force", "no external torque", "friction present"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 140,
    subject: "physics",
    text: "A vector quantity must always have:",
    options: ["magnitude only", "direction only", "both magnitude and direction", "time dependency"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 141,
    subject: "physics",
    text: "Work becomes negative when angle between force and displacement is:",
    options: ["acute", "0°", "obtuse", "90°"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 142,
    subject: "physics",
    text: "If acceleration is opposite to velocity, object:",
    options: ["speeds up", "slows down", "moves in circle", "stays constant"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 143,
    subject: "physics",
    text: "Weight changes with:",
    options: ["mass", "height only", "gravity", "velocity"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 144,
    subject: "physics",
    text: "Unit vector magnitude is always:",
    options: ["0", "1", "depends", "infinite"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 145,
    subject: "physics",
    text: "Newton’s first law is valid in:",
    options: ["non-inertial frame", "inertial frame", "accelerating frame only", "rotating frame only"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 146,
    subject: "physics",
    text: "Two equal opposite forces on different bodies:",
    options: ["cancel each other", "produce zero motion", "do not cancel", "always increase motion"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 147,
    subject: "physics",
    text: "Energy is scalar because:",
    options: ["it has direction", "it has magnitude only", "it is conserved", "it depends on force"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 148,
    subject: "physics",
    text: "If velocity is zero, acceleration must be:",
    options: ["zero always", "maximum", "may or may not be zero", "infinite"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 149,
    subject: "physics",
    text: "Resultant of 6N and 8N at 90°:",
    options: ["10N", "14N", "2N", "12N"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 150,
    subject: "physics",
    text: "A force of 15N acts on 3kg body:",
    options: ["3 m/s²", "5 m/s²", "45 m/s²", "12 m/s²"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 151,
    subject: "physics",
    text: "Work done by 20N force over 2m at 60°:",
    options: ["20J", "40J", "20√3 J", "10J"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 152,
    subject: "physics",
    text: "KE of 2kg body moving at 3 m/s:",
    options: ["6J", "9J", "12J", "18J"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 153,
    subject: "physics",
    text: "Power = 200W for 4s, energy:",
    options: ["800J", "600J", "400J", "200J"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 154,
    subject: "physics",
    text: "v = rω, r = 5m, ω = 2 rad/s:",
    options: ["5 m/s", "10 m/s", "7 m/s", "12 m/s"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 155,
    subject: "physics",
    text: "If mass doubles and velocity halves, momentum:",
    options: ["doubles", "halves", "remains same", "becomes zero"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 156,
    subject: "physics",
    text: "1 horsepower equals:",
    options: ["746W", "500W", "100W", "1000W"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 157,
    subject: "physics",
    text: "Centripetal force depends on:",
    options: ["r only", "v only", "mv²/r", "mgh"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 158,
    subject: "physics",
    text: "Work done is zero when force is:",
    options: ["parallel", "perpendicular", "opposite", "inclined"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 159,
    subject: "physics",
    text: "A body moves in circle at constant speed. Its acceleration:",
    options: ["zero", "outward", "inward", "tangential only"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 160,
    subject: "physics",
    text: "If net force is zero, object:",
    options: ["must stop", "accelerates", "maintains velocity", "rotates"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 161,
    subject: "physics",
    text: "Scalar quantity is:",
    options: ["force", "displacement", "work", "velocity"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 162,
    subject: "physics",
    text: "A system with no external force:",
    options: ["gains energy", "loses energy", "conserves momentum", "stops motion"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 163,
    subject: "english",
    text: "Choose correct sentence:",
    options: ["He go to school daily", "He goes to school daily", "He going to school daily", "He gone to school"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 164,
    subject: "english",
    text: "Synonym of “Rapid”:",
    options: ["Slow", "Fast", "Weak", "Lazy"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 165,
    subject: "english",
    text: "Antonym of “Increase”:",
    options: ["Grow", "Reduce", "Expand", "Rise"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 166,
    subject: "english",
    text: "Fill in the blank: She is good ___ mathematics.",
    options: ["in", "at", "on", "for"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 167,
    subject: "english",
    text: "Correct spelling:",
    options: ["Enviroment", "Environment", "Environmant", "Envirenment"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 168,
    subject: "english",
    text: "One word for “A person who writes books”:",
    options: ["Editor", "Author", "Publisher", "Reader"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 169,
    subject: "english",
    text: "Choose correct tense: He ___ already finished the work.",
    options: ["has", "have", "had", "having"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 170,
    subject: "english",
    text: "Error spotting: He don't like tea.",
    options: ["He", "don't", "like", "tea"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 171,
    subject: "english",
    text: "Comprehension: “The sun rises in the east.” Conclusion:",
    options: ["Sun rises west", "Sun rises east", "Sun sets east", "No relation"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 172,
    subject: "logical_reasoning",
    text: "If ALL cats are animals and SOME animals are dogs, then:",
    options: ["All cats are dogs", "Some cats are dogs", "Cats are animals only", "No conclusion"],
    correctIndex: 3,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 173,
    subject: "logical_reasoning",
    text: "Find next number: 2, 6, 12, 20, 30, ?",
    options: ["40", "41", "42", "44"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 174,
    subject: "logical_reasoning",
    text: "Odd one out:",
    options: ["Apple", "Banana", "Carrot", "Mango"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 175,
    subject: "logical_reasoning",
    text: "If A > B and B > C, then:",
    options: ["C > A", "A > C", "B < A always false", "No relation"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 176,
    subject: "logical_reasoning",
    text: "Coding: CAT = DBU, then DOG = ?",
    options: ["EPH", "EPJ", "FQH", "EQH"],
    correctIndex: 0,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 177,
    subject: "logical_reasoning",
    text: "A is brother of B, B is sister of C. A is C’s:",
    options: ["Father", "Brother", "Uncle", "Cousin"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 178,
    subject: "logical_reasoning",
    text: "Find next letter: A, C, F, J, O, ?",
    options: ["T", "U", "V", "W"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 179,
    subject: "logical_reasoning",
    text: "Statement: All pens are books. Some books are papers. Conclusion:",
    options: ["Some pens are papers", "No conclusion", "All papers are pens", "Some books are pens"],
    correctIndex: 1,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
  {
    id: 180,
    subject: "logical_reasoning",
    text: "Direction: A walks north, then east, then south. He is facing:",
    options: ["North", "East", "South", "West"],
    correctIndex: 2,
    explanation: "Refer to the relevant MDCAT syllabus unit for a detailed explanation of this concept.",
  },
];
